<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access to our dashboard' => 'Uone dashibodi!',
    'Congratulations!' => 'Pongezi!',
    'This is a string to translate!' => 'Hii ni ya kutafsiri!',
    'Account Created Successfully, Account activate link has sent to your Email' => '',
    'Added Criteria Required for Shortlist' => '',
    'All application must be reviewed' => '',
    'Allocated Successfully' => '',
    'Back to Home' => '',
    'CHURCH MANAGEMENT SYSTEM TEAM' => '',
    'Change Password' => '',
    'Child' => '',
    'Church Management System' => '',
    'Church Management System Team' => '',
    'Click to refresh the code' => '',
    'Created At' => '',
    'Data' => '',
    'Deleted Successfully' => '',
    'Description' => '',
    'Email' => '',
    'Email Sent Successfully' => '',
    'Email not registered' => '',
    'Enter your email to get a password reset link' => '',
    'First Name' => '',
    'Forget Password' => '',
    'Forget password' => '',
    'Forgot password?' => '',
    'ID' => '',
    'Invalid Licence number.' => '',
    'Invalid activate link or the link has expired' => '',
    'Invalid email or password' => '',
    'Invalid reset password link or the link has expired' => '',
    'Invalid rule "{value}"' => '',
    'Item Name' => '',
    'Language:' => '',
    'Login' => '',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.' => '',
    'Middle Name' => '',
    'Ministry of Health' => '',
    'Name' => '',
    'Not Allocated Successfully' => '',
    'POSTGRADUATE SPONSORSHIP APPLICATION PORTAL' => '',
    'Parent' => '',
    'Password' => '',
    'Password successfully Set' => '',
    'Phone Number' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please set at least one added criteria' => '',
    'Postgraduate Sponsorship Application Portal' => '',
    'Problem on getting person information from council please contact help desk for support' => '',
    'ROMAN CATHOLIC' => '',
    'Register' => '',
    'Register to Esponsorship  Portal' => '',
    'Reset Password' => '',
    'Review Session Opened' => '',
    'Reviewed Successfully' => '',
    'Rule "{value}" does not exists' => '',
    'Rule Name' => '',
    'Saved Successfully' => '',
    'Session closed Until Next time' => '',
    'Sex' => '',
    'Something went wrong' => '',
    'Sorry user with this email address is already exists' => '',
    'Sponsored Applicant cant Update Names' => '',
    'Successfully, Please Check your email to set new password' => '',
    'Surname' => '',
    'The United Republic of Tanzania' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'The requested page does not exist.' => '',
    'Type' => '',
    'Updated Successfully' => '',
    'User ID' => '',
    'Users' => '',
    'Varification Code' => '',
    'Verification Code' => '',
    'Verification code' => '',
    'You have submitted application, 
                our team are reviewing your application you can not update your profile' => '',
    'login' => '',
    'Roman Catholic' => '@@Kanisa katoliki@@',
];
